version: '3.2'

volumes:
  store-postgres:
    driver: local

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    image: postgres:9.6
    container_name: store-postgres
    volumes:
      - type: volume
        source: store-postgres
        target: /var/lib/postgresql/dataConfig
    networks:
      - postgres-network
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5435:5432"
